dist: trusty
sudo: false
matrix:
  include:
  - language: go
    go:
    - 1.11
    env:
    - GOMAXPROCS=4
    os:
    - linux
    install:
    - go get github.com/axw/gocov/gocov
    - go install github.com/axw/gocov/gocov
    - go get github.com/prometheus/client_golang/prometheus
    - go get github.com/prometheus/client_golang/prometheus/promauto
    - go get github.com/prometheus/client_golang/prometheus/promhttp
    - go get -u github.com/gorilla/mux
    before_install:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - go test -race -v -coverprofile=c.out github.com/mchirico/go_script/...
    - gocov test github.com/mchirico/go_script/... > cc.out
    after_success:
    - # mv c0.out  c.out
    - # tail c1.out -n+1 >> c.out
    - bash <(curl -s https://codecov.io/bash)
    - pwd
    - find . -iname '*c.out*'
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"




