dist: trusty
sudo: false
matrix:
  include:
  - language: go
    go:
    - 1.11
    env:
    - GOMAXPROCS=4
    os:
    - linux
    install:
    - go get github.com/prometheus/client_golang/prometheus
    - go get github.com/prometheus/client_golang/prometheus/promauto
    - go get github.com/prometheus/client_golang/prometheus/promhttp
    - go get -u github.com/gorilla/mux
    before_install:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - go test -race -v -coverprofile=c0.out github.com/mchirico/go_script/pkg
    - go test -race -v -coverprofile=c1.out github.com/mchirico/go_script/prometheus        
    after_success:
    - cat c0.out c1.out > c.out
    - bash <(curl -s https://codecov.io/bash)
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"




